language: ruby
rvm:
  - 2.6.3
  - jruby
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
addons:
  postgresql: "11.5"
test:
  adapter: postgresql
  database: travis_ci_test
env:
  global:
  - PGPORT=5433